Diagnostic Output for AFMV
Seneca-CDOT/gcc pull request #18
Opened 2024-04-22 09:11 UTC by code-Gambler

This PR closes the this Issue.
#17 

It adds a test gimple pass which prints "Hello World" for now, but In the future I would like to integrate it with cloning and pruning and provide some diagnostic output to the developer .

2024-04-22 19:56 UTC, MatthewDeNapoli requested changes

2024-04-22 19:56 UTC, MatthewDeNapoli commented on gcc/test.cc
> +    bool gate(function*) final override {
move the return type to the line above

2024-04-22 19:56 UTC, MatthewDeNapoli commented on gcc/test.cc
> +    unsigned int execute(function*) final override {
move the return type to the line above

2024-04-22 19:56 UTC, MatthewDeNapoli commented on gcc/test.cc
> +gimple_opt_pass * make_pass_test_dump(gcc::context * ctxt) {
move the return type to the line above

2024-04-23 01:28 UTC, code-Gambler commented
Changes Done!

2024-04-23 01:36 UTC, MatthewDeNapoli approved these changes

2024-04-23 01:36 UTC, merged